### ISSUE TITLE
Optimise memory usage

### ISSUE THREAD

**Issue by stereobooster** [SixArm/sixarm_ruby_unaccent#1]
Optimise memory usage the same way as [mini_mime](https://github.com/discourse/mini_mime/) done for [mime-types](https://github.com/mime-types/ruby-mime-types/)

```
bundle exec derailed bundle:objects | head -n 100
Measuring objects created by gems in groups [:default, "production"]

allocated memory by gem
-----------------------------------
   2246417  sixarm_ruby_unaccent-1.1.1
```

Still looking into ways to improve this. Maybe Rust?..

**Comment by joelparkerhenderson** [comment]
Thanks, I'll take a look today.

**Comment by pnomolos** [comment]
@joelparkerhenderson I've modified the gem to use the `unac` library rather than native ruby.  Would you like me to open a pull request? https://github.com/pnomolos/sixarm_ruby_unaccent/tree/pnomolos/use_unac_extension

I used `String::ACCENTMAP` to compare implementations and the only differences I saw were the following, which seem like they may have been incorrect before?

| Character | pure-ruby | unac |
| --------- | --------- | ---- |
| ℃         | ଌ         | °C   |
| ℉        | ଏ         | °F   |

I'm using this (via the countries gem) on some internal tools that parse rather large (100s MBs) CSV files.  More than the size of the memory allocations were the number of allocations for the pure-ruby implementation (millions) were making Ruby's GC rather unhappy.

**Comment by joelparkerhenderson** [comment]
Excellent work, and yes please for a PR. Thank you!

**Comment by pnomolos** [comment]
@joelparkerhenderson In thinking about it, I'm wondering if it wouldn't be better for the pure-ruby gem to stay as it is (although I have some ideas for optimization that I need to run some tests on) and instead provide a `sixarm_ruby_unaccent-extension` gem that uses the C extension.  As the `countries` gem depends on this one, I don't want to force a native extension on people who may not want it or be unable to use it.

**Comment by joelparkerhenderson** [comment]
You make a good point. 

I've run into this with the JSON gem and it was rough going. My personal preference is for the basename to use solely Ruby, which tends to be easier for novices to read, and also friendlier to use in more environments.

Although, the JSON gem chose the opposite, i.e. `json` uses C whereas `json-pure` uses all Ruby.

I'm fine either way; let me know what you would like to happen.

When you decide, I'd like to release it named as `unaccent` in addition to `sixarm_ruby_unaccent` because most developers prefer the shorter name. :)

Thanks!

**Comment by pnomolos** [comment]
@joelparkerhenderson I've been doing some performance benchmarking of a few different algorithms on various text sources (small -> large, no replacements -> many replacements).  I'll hopefully have one picked and a PR for you early next week, although with some more in-depth tests :)

In terms of the gem, I definitely would recommend that `unaccent` is pure ruby and `unaccent-ext` (or whatever it's called) is the one with the native extension.

**Comment by joelparkerhenderson** [comment]
Sounds good. Are you familiar with minitest benchmark? It's nifty little way to add benchmark tests, such as sanity checks to ensure an algorithm is O(n).

**Comment by joelparkerhenderson** [comment]
Good, thanks. I updated the master branch to help the pure ruby version:

  * Configure Travis for Ruby 2.4, 2.3, 2.2, 2.1, 2., and remove RBX until someone else wants it.

  * Change the algorithm from typical Ruby 1.x (split map join) to Ruby 2.x (each_char append). 

  * Bundle update.

Travis is succeeding. See https://travis-ci.org/SixArm/sixarm_ruby_unaccent

Benchmark of the new algorithm shows ~2x faster on my MacBook.

I have some fixes to do with the gemspec format, then I'll publish the gem.

**Comment by stereobooster** [comment]
Another idea: we can use crystal to compile this gem to native, if we lucky enough we will not need to change any ruby code
